import Stripe from 'stripe';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Configuration for products and prices
const PRODUCTS_CONFIG = {
  credits: {
    name: 'Viral Shorts Generator - Credits',
    description: 'Purchase credits to generate viral shorts scripts',
    packages: [
      {
        name: '10 Credits',
        credits: 10,
        price: 999, // $9.99
      },
      {
        name: '50 Credits',
        credits: 50,
        price: 3999, // $39.99
      },
      {
        name: '100 Credits',
        credits: 100,
        price: 6999, // $69.99
      },
    ],
  },
  subscriptions: {
    pro: {
      name: 'Viral Shorts Generator - Pro',
      description: 'Unlimited script generation with priority support',
      price: 2900, // $29/month
      interval: 'month',
    },
    agency: {
      name: 'Viral Shorts Generator - Agency',
      description: 'Unlimited script generation, team management, and advanced features',
      price: 9900, // $99/month
      interval: 'month',
    },
  },
};

async function setupStripe() {
  const apiKey = process.env.STRIPE_SECRET_KEY;

  if (!apiKey) {
    console.error('❌ Error: STRIPE_SECRET_KEY environment variable is not set');
    console.error('Please set your Stripe secret key and try again');
    process.exit(1);
  }

  const stripe = new Stripe(apiKey);
  const priceIds = {};

  try {
    console.log('🚀 Starting Stripe setup...\n');

    // Create credit packages
    console.log('📦 Creating credit packages...');
    const creditsProduct = await stripe.products.create({
      name: PRODUCTS_CONFIG.credits.name,
      description: PRODUCTS_CONFIG.credits.description,
      type: 'service',
      metadata: {
        type: 'credits',
      },
    });

    console.log(`✓ Created product: ${creditsProduct.name} (${creditsProduct.id})`);

    for (const pkg of PRODUCTS_CONFIG.credits.packages) {
      const price = await stripe.prices.create({
        product: creditsProduct.id,
        unit_amount: pkg.price,
        currency: 'usd',
        metadata: {
          credits: pkg.credits.toString(),
        },
      });

      const envKey = `STRIPE_PRICE_CREDITS_${pkg.credits}`;
      priceIds[envKey] = price.id;
      console.log(`  ✓ ${pkg.name}: ${price.id}`);
    }

    // Create subscription plans
    console.log('\n💳 Creating subscription plans...');

    for (const [planKey, planConfig] of Object.entries(PRODUCTS_CONFIG.subscriptions)) {
      const product = await stripe.products.create({
        name: planConfig.name,
        description: planConfig.description,
        type: 'service',
        metadata: {
          type: 'subscription',
          plan: planKey,
        },
      });

      console.log(`✓ Created product: ${product.name} (${product.id})`);

      const price = await stripe.prices.create({
        product: product.id,
        unit_amount: planConfig.price,
        currency: 'usd',
        recurring: {
          interval: planConfig.interval,
        },
        metadata: {
          plan: planKey,
        },
      });

      const envKey = `STRIPE_PRICE_${planKey.toUpperCase()}`;
      priceIds[envKey] = price.id;
      console.log(`  ✓ Price ID: ${price.id}`);
    }

    // Generate .env.local file with price IDs
    console.log('\n📝 Generating environment configuration...');

    let envContent = `# Stripe Configuration (Auto-generated by setup-stripe.mjs)
# Generated: ${new Date().toISOString()}

# Stripe API Keys
STRIPE_SECRET_KEY=${apiKey}
VITE_STRIPE_PUBLISHABLE_KEY=pk_test_YOUR_PUBLISHABLE_KEY_HERE

# Stripe Product Price IDs
STRIPE_PRICE_CREDITS_10=${priceIds.STRIPE_PRICE_CREDITS_10}
STRIPE_PRICE_CREDITS_50=${priceIds.STRIPE_PRICE_CREDITS_50}
STRIPE_PRICE_CREDITS_100=${priceIds.STRIPE_PRICE_CREDITS_100}
STRIPE_PRICE_PRO=${priceIds.STRIPE_PRICE_PRO}
STRIPE_PRICE_AGENCY=${priceIds.STRIPE_PRICE_AGENCY}

# Stripe Webhook Secret (Set this after configuring webhooks in Stripe Dashboard)
STRIPE_WEBHOOK_SECRET=whsec_YOUR_WEBHOOK_SECRET_HERE
`;

    const envPath = path.join(__dirname, '..', '.env.stripe');
    fs.writeFileSync(envPath, envContent);

    console.log(`✓ Created .env.stripe file at ${envPath}`);

    // Display summary
    console.log('\n✅ Stripe setup completed successfully!\n');
    console.log('📋 Summary:');
    console.log('━'.repeat(60));
    console.log('Credit Packages:');
    console.log(`  • 10 Credits: ${priceIds.STRIPE_PRICE_CREDITS_10}`);
    console.log(`  • 50 Credits: ${priceIds.STRIPE_PRICE_CREDITS_50}`);
    console.log(`  • 100 Credits: ${priceIds.STRIPE_PRICE_CREDITS_100}`);
    console.log('\nSubscription Plans:');
    console.log(`  • Pro ($29/month): ${priceIds.STRIPE_PRICE_PRO}`);
    console.log(`  • Agency ($99/month): ${priceIds.STRIPE_PRICE_AGENCY}`);
    console.log('━'.repeat(60));

    console.log('\n📌 Next steps:');
    console.log('1. Copy the price IDs from above to your .env file');
    console.log('2. Set VITE_STRIPE_PUBLISHABLE_KEY in your .env file');
    console.log('3. Configure webhook endpoint in Stripe Dashboard:');
    console.log('   - Go to https://dashboard.stripe.com/webhooks');
    console.log('   - Add endpoint: https://your-domain.com/api/webhooks/stripe');
    console.log('   - Select events: checkout.session.completed, customer.subscription.updated');
    console.log('4. Copy the webhook signing secret to STRIPE_WEBHOOK_SECRET');

    process.exit(0);
  } catch (error) {
    console.error('❌ Error setting up Stripe:', error.message);
    process.exit(1);
  }
}

setupStripe();
